let autos =[{
    marca:"Ford" ,
    modelo:"Fiesta" ,
    precio:150000,
    km:200,
    color:"Azul",
    cuotas:12 , 
    anio:2019,
    patente:"APL123" ,
    vendido:false},

   {marca:"Toyota" ,
    modelo:"Corolla" ,
    precio:100000,
    km:0 ,
    color:"Blanco",
    cuotas:14,
    anio:2019,
    patente:"JJK117",
    vendido:false},

    {marca:"Nissan" ,
    modelo:"Future" ,
    precio:50000,
    km:0 ,
    color:"Blanco",
    cuotas:14,
    anio:2019,
    patente:"JJK216",
    vendido:false},
    
    {marca:"Nissan" ,
    modelo:"Mundial" ,
    precio:900000,
    km:0 ,
    color:"Verde",
    cuotas:14,
    anio:2020,
    patente:"JJK216",
    vendido:true}
]
module.exports=autos